# Generated by Django 2.2.2 on 2019-06-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0004_auto_20190615_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(default='<...To be set later...>', to='imdb_app.Genre'),
        ),
    ]
